### ISSUE TITLE
Attribute definition request for "Z"

### ISSUE THREAD

**Issue by koustov** [koustov/css-builder#36]
## Attribute Prefix
Attributes start with "Z"

## Is for an entire prefix or partial implementation 
Full

## If partial, mention segment count
NA

## Definition template

All the attribute definitions are maintained under [definitions](/src/definitions ) directory and here is the template
Template:
```
[
  {
    "display": "<Display Name>",
    "description": "<A very simple description, not going much technical>",
    "link": "<External link to get more details>",
    "propertyName": "<Underneath attribute name>",
    "valuetemplate": "<The template for the value>",
    "categories": ["<A list of categories this attribute can belong>"], 
    "tags": "<A comma separated values for adding tags which is more internal for filter/search etc>",
    "controls": [<List of controls that is required to build the value>]
  }
]
```

**Comment by eemike07** [comment]
Hello there~!
Could you assign me this one?  Could also take care of additional ones after knocking this one out.

**Comment by koustov** [comment]
> Hello there~! Could you assign me this one? Could also take care of additional ones after knocking this one out.

assigned

**Comment by eemike07** [comment]
Can you update the tags to `hacktoberfest`?  `hactoberfest` is misspelled
