### ISSUE TITLE
Scrolling Is not Working

### ISSUE THREAD

**Issue by donjosemathew** [koustov/css-builder#50]
**Is your feature request related to a problem? Please describe.**
The Scrollbar is not showing. Components are overlapping
**Describe the solution you'd like**
Add Overflow-y to auto
**Describe alternatives you've considered**

**Additional context**
Can I work On this issue?

**Comment by koustov** [comment]
@dontech09 i have assigned it.

**Comment by koustov** [comment]
@all-contributors please add @dontech09  for bug

**Comment by koustov** [comment]
PR merged
